"""Official Python SDK for the OTP.ID V3 API."""

from __future__ import annotations

from otpid.client import Client
from otpid.errors import (
    ERR_ALREADY_USED,
    ERR_CHANNEL_UNAVAILABLE,
    ERR_DESTINATION_RATE_LIMITED,
    ERR_DUPLICATE_EXTERNAL_ID,
    ERR_INSUFFICIENT_BALANCE,
    ERR_INTERNAL,
    ERR_INVALID_CHANNEL,
    ERR_INVALID_NUMBER,
    ERR_INVALID_RESPONSE,
    ERR_IP_NOT_ALLOWED,
    ERR_OTP_EXPIRED,
    ERR_OTP_NOT_FOUND,
    ERR_RATE_LIMITED,
    ERR_TOO_MANY_ATTEMPTS,
    ERR_UNAUTHORIZED,
    ERR_VALIDATION,
    APIError,
    InvalidSignatureError,
    OtpIdError,
    StaleTimestampError,
    UnexpectedEventError,
)
from otpid.types import (
    CHANNEL_EMAIL,
    CHANNEL_MISSCALL,
    CHANNEL_SMS,
    CHANNEL_VOICE,
    CHANNEL_WHATSAPP,
    CHANNEL_WHATSAPP_INBOUND,
    FAILURE_CHANNEL_UNAVAILABLE,
    FAILURE_DELIVERY_FAILED,
    FAILURE_NUMBER_NOT_ON_WHATSAPP,
    FAILURE_PROVIDER_UNAVAILABLE,
    FAILURE_TOO_FREQUENT,
    AccountResult,
    Channel,
    DeliveryFailure,
    OrderResult,
    StatusResult,
    TopupResult,
    Verification,
    VerifiedEvent,
    VerifyResult,
)
from otpid.webhook import (
    WEBHOOK_TOLERANCE_SECONDS,
    parse_verified_event,
    verify_webhook_signature,
)

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "Client",
    "ERR_UNAUTHORIZED",
    "ERR_VALIDATION",
    "ERR_INVALID_CHANNEL",
    "ERR_INVALID_NUMBER",
    "ERR_INSUFFICIENT_BALANCE",
    "ERR_OTP_NOT_FOUND",
    "ERR_DUPLICATE_EXTERNAL_ID",
    "ERR_OTP_EXPIRED",
    "ERR_TOO_MANY_ATTEMPTS",
    "ERR_ALREADY_USED",
    "ERR_RATE_LIMITED",
    "ERR_DESTINATION_RATE_LIMITED",
    "ERR_CHANNEL_UNAVAILABLE",
    "ERR_IP_NOT_ALLOWED",
    "ERR_INTERNAL",
    "ERR_INVALID_RESPONSE",
    "OtpIdError",
    "APIError",
    "InvalidSignatureError",
    "StaleTimestampError",
    "UnexpectedEventError",
    "Channel",
    "CHANNEL_WHATSAPP",
    "CHANNEL_SMS",
    "CHANNEL_VOICE",
    "CHANNEL_EMAIL",
    "CHANNEL_MISSCALL",
    "CHANNEL_WHATSAPP_INBOUND",
    "FAILURE_NUMBER_NOT_ON_WHATSAPP",
    "FAILURE_TOO_FREQUENT",
    "FAILURE_CHANNEL_UNAVAILABLE",
    "FAILURE_PROVIDER_UNAVAILABLE",
    "FAILURE_DELIVERY_FAILED",
    "Verification",
    "DeliveryFailure",
    "OrderResult",
    "VerifyResult",
    "StatusResult",
    "AccountResult",
    "TopupResult",
    "VerifiedEvent",
    "WEBHOOK_TOLERANCE_SECONDS",
    "verify_webhook_signature",
    "parse_verified_event",
]
